KarcicegiYayinVeDagitim/Controllers/CategoryController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using KarcicegiYayinVeDagitim.Entity;
using KarcicegiYayinVeDagitim.Models;

namespace KarcicegiYayinVeDagitim.Controllers
{
    public class CategoryController : Controller
    {
        private DataContext db = new DataContext();

        // GET: Category
        [Authorize(Roles = "admin")]
        public ActionResult Index()
        {
            return View(db.Categories.ToList());
        }
        public PartialViewResult CategoryList()
        {
            var kategoriler = db.Categories.Select(x => new CategoryModel()
            {
                Id = x.Id,
                Name = x.Name,
                Count = x.Products.Count()
            }).ToList();
            return PartialView(kategoriler);
        }
        public PartialViewResult CategoryListNavbar()
        {
            var kategoriler = db.Categories.Select(x => new CategoryModel()
            {
                Id = x.Id,
                Name = x.Name,
                Count = x.Products.Count()
            }).ToList();
            return PartialView(kategoriler);
        }

        // GET: Category/Details/5
        [Authorize(Roles = "admin")]
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Category category = db.Categories.Find(id);
            if (category == null)
            {
                return HttpNotFound();
            }
            return View(category);
        }

        // GET: Category/Create
        [Authorize(Roles = "admin")]
        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "admin")]
        public ActionResult Create([Bind(Include = "Id,Name,Description")] Category category)
        {
            if (ModelState.IsValid)
            {
                db.Categories.Add(category);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(category);
        }

        // GET: Category/Edit/5
        [Authorize(Roles = "admin")]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Category category = db.Categories.Find(id);
            if (category == null)
            {
                return HttpNotFound();
            }
            return View(category);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "admin")]
        public ActionResult Edit([Bind(Include = "Id,Name,Description")] Category category)
        {
            if (ModelState.IsValid)
            {
                db.Entry(category).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(category);
        }

        // GET: Category/Delete/5
        [Authorize(Roles = "admin")]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Category category = db.Categories.Find(id);
            if (category == null)
            {
                return HttpNotFound();
            }
            return View(category);
        }

        // POST: Category/Delete/5
        [Authorize(Roles = "admin")]
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Category category = db.Categories.Find(id);
            db.Categories.Remove(category);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

KarcicegiYayinVeDagitim/Controllers/HomeController.cs
using KarcicegiYayinVeDagitim.Entity;
using KarcicegiYayinVeDagitim.Models;
using System;
using System.Collections.Generic;
using System.Drawing.Printing;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace KarcicegiYayinVeDagitim.Controllers
{
    public class HomeController : Controller
    {
        DataContext db = new DataContext();
        // GET: Home
        public ActionResult Index()
        {
            var urun = db.Products.Where(i => i.IsHome && i.IsApproved).Select(i => new ProductModel()
            {
                Id = i.Id,
                Name = i.Name,
                Description = i.Description.Length > 25 ? i.Description.Substring(0, 20) + "..." : i.Description,
                Class = i.Class,
                Price = i.Price,
                Stok = i.Stok,
                Image = i.Image,
                CategoryId = i.CategoryId
            }).ToList();
            return View(urun);
        }
        public PartialViewResult Slider()
        {
            return PartialView(db.Products.Where(x => x.Slider && x.IsApproved).Take(5).ToList());
        }
        public PartialViewResult FeaturedProductList()
        {
            return PartialView(db.Products.Where(x => x.Isfeatured && x.IsApproved).Take(5).ToList());
        }
        public ActionResult ProductList(int id )
        {
            return View(db.Products.Where(i => i.CategoryId == id).ToList());
        }
        public ActionResult ProductDetails(int id)
        {
            return View(db.Products.Where(x => x.Id == id).FirstOrDefault());
        }
        public ActionResult Search(string q)
        {
            var arama = db.Products.Where(x => x.IsApproved == true);
            if (string.IsNullOrEmpty(q))
            {
                arama.Where(i => i.Name.Contains(q) || i.Description.Contains(q));
            }
            return View(arama.ToList());
        }
        public ActionResult Product()
        {
            var urun = db.Products.Where(i => i.IsApproved).Select(i => new ProductModel()
            {
                Id = i.Id,
                Name = i.Name,
                Description = i.Description.Length > 25 ? i.Description.Substring(0, 20) + "..." : i.Description,
                Class = i.Class,
                Price = i.Price,
                Stok = i.Stok,
                Image = i.Image,
                CategoryId = i.CategoryId
            }).ToList();
            return View(urun);
        }



    }
}

KarcicegiYayinVeDagitim/Controllers/ProductController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using KarcicegiYayinVeDagitim.Entity;

namespace KarcicegiYayinVeDagitim.Controllers
{
    public class ProductController : Controller
    {
        private DataContext db = new DataContext();
        // GET: Product
        [Authorize(Roles = "admin")]
        public ActionResult Index()
        {
            var products = db.Products.Include(p => p.Category);
            return View(products.ToList());
        }
        // GET: Product/Details/5
        [Authorize(Roles = "admin")]
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Product product = db.Products.Find(id);
            if (product == null)
            {
                return HttpNotFound();
            }
            return View(product);
        }
        // GET: Product/Create
        [Authorize(Roles = "admin")]
        public ActionResult Create()
        {
            ViewBag.CategoryId = new SelectList(db.Categories, "Id", "Name");
            return View();
        }
        [Authorize(Roles = "admin")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Product model, HttpPostedFileBase File)
        {
            string path = Path.Combine("~/Content/Image/" + File.FileName);
            File.SaveAs(Server.MapPath(path));
            model.Image = File.FileName.ToString();
            db.Products.Add(model);
            db.SaveChanges();
            return RedirectToAction("index");
        }
        // GET: Product/Edit/5
        [Authorize(Roles = "admin")]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Product product = db.Products.Find(id);
            if (product == null)
            {
                return HttpNotFound();
            }
            ViewBag.CategoryId = new SelectList(db.Categories, "Id", "Name", product.CategoryId);
            return View(product);
        }
        [Authorize(Roles = "admin")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Name,Description,Class,Price,Stok,Image,Slider,IsHome,IsApproved,Isfeatured,CategoryId")] Product product)
        {
            if (ModelState.IsValid)
            {
                db.Entry(product).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.CategoryId = new SelectList(db.Categories, "Id", "Name", product.CategoryId);
            return View(product);
        }
        // GET: Product/Delete/5
        [Authorize(Roles = "admin")]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Product product = db.Products.Find(id);
            if (product == null)
            {
                return HttpNotFound();
            }
            return View(product);
        }
        // POST: Product/Delete/5
        [Authorize(Roles = "admin")]
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Product product = db.Products.Find(id);
            db.Products.Remove(product);
            db.SaveChanges();
            return RedirectToAction("Index");
        }
        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

KarcicegiYayinVeDagitim/Views/Home/FeaturedProductList.cshtml
@using KarcicegiYayinVeDagitim.Entity
@model IEnumerable<Product>
<h5>POPÜLER ÜRÜNLER</h5>
@foreach (var item in Model)
{
    <div class="thumbnail" style="width:260px; height:210px;">
        <img src="~/Content/image/@item.Image" alt="Bootshop panasonoc New camera" style="width:125px; height:90px;" />
        <div class="caption">
            <h5><a href="/Home/ProductDetails/@item.Id">@item.Name.ToUpper()</a></h5>
            <h4 style="text-align:center"><a class="btn" href="/Home/ProductDetails/@item.Id">Görüntüle <i class="icon-shopping-cart"></i></a> <a class="btn btn-primary" href="#">@item.Price (₺)</a></h4>
        </div>
    </div>
    <br />
}

KarcicegiYayinVeDagitim/Views/Home/Index.cshtml
@using KarcicegiYayinVeDagitim.Models
@model IEnumerable<ProductModel>
@{
    ViewBag.Title = "Index";
}

@Html.Action("Slider", "Home")
<br />
@Html.Action("CategoryListNavbar","Category")
<div id="mainBody">
    <div class="container">
        <div class="row">
            <!-- Sidebar ================================================== -->
            <div id="sidebar" class="span3">
                @Html.Action("Summary", "Cart")
                <ul id="sideManu" class="nav nav-tabs nav-stacked">

                    @Html.Action("CategoryList", "Category")

                </ul>
                <br />
                @Html.Action("FeaturedProductList", "Home")
            </div>
            <!-- Sidebar end=============================================== -->
            <div class="span9">
                <h4>Latest Products </h4>
                <ul class="thumbnails">
                    @foreach (var item in Model)
                    {

                        <li class="span3">
                            <div class="thumbnail" style="width:270px;height:310px">
                                <a href="/Home/ProductDetails/@item.Id"><img style="width:160px;height:200px;max-width:160px;max-height:250px" src="~/Content/image/@item.Image" alt="" /></a>
                                <div class="caption" style="width:260px;height:140px">
                                    <h5><a href="/Home/ProductDetails/@item.Id">@item.Name</a></h5>
                                    <p>
                                        @item.Description
                                    </p>

                                    <h4 style="text-align:center"><a class="btn" href="/Home/ProductDetails/@item.Id">Görüntüle..<i class="icon-shopping-cart"></i></a> <a class="btn btn-primary">@item.Price (₺)</a></h4>
                                </div>
                            </div>
                        </li>
                    }
                </ul>

            </div>
        </div>
    </div>
</div>

KarcicegiYayinVeDagitim/Views/Home/Product.cshtml
@using KarcicegiYayinVeDagitim.Models
@model IEnumerable<ProductModel>
@{
    ViewBag.Title = "Product";
}
@Html.Action("CategoryListNavbar", "Category")
<div id="mainBody">
    <div class="container">
        <div class="row">
            <!-- Sidebar ================================================== -->
            <div id="sidebar" class="span3">
                @Html.Action("Summary", "Cart")
                <ul id="sideManu" class="nav nav-tabs nav-stacked">
                    @Html.Action("CategoryList", "Category")
                </ul>
                <br>
                @Html.Action("FeaturedProductList", "Home")
            </div>
            <!-- Sidebar end=============================================== -->
            <div class="span9">
                <ul class="breadcrumb">
                    <li><a href="index.html">Home</a> <span class="divider">/</span></li>
                    <li class="active">Products</li>
                </ul>
                <h3> Tüm Kitaplar </h3>


                <br class="clr">
                <div class="tab-content">
                    <div class="tab-pane  active" id="blockView">
                        <ul class="thumbnails">
                            @foreach (var item in Model)
                            {

                                <li class="span3">
                                    <div class="thumbnail" style="width:270px;height:310px">
                                        <a href="/Home/ProductDetails/@item.Id"><img style="width:160px;height:200px;max-width:160px;max-height:250px" src="~/Content/image/@item.Image" alt="" /></a>
                                        <div class="caption" style="width:260px;height:140px">
                                            <h5><a href="/Home/ProductDetails/@item.Id">@item.Name.ToUpper()</a></h5>
                                            <p>
                                                @item.Description.ToUpper()
                                            </p>

                                            <h4 style="text-align:center"><a class="btn" href="/Home/ProductDetails/@item.Id">Görüntüle..<i class="icon-shopping-cart"></i></a> <a class="btn btn-primary">@item.Price (₺)</a></h4>
                                        </div>
                                    </div>
                                </li>
                            }
                        </ul>
                        <hr class="soft">
                    </div>
                </div>
                <br class="clr">
            </div>
        </div>
    </div>
</div>

KarcicegiYayinVeDagitim/Views/Home/ProductDetails.cshtml
@using KarcicegiYayinVeDagitim.Entity
@model Product
@{
    ViewBag.Title = "ProductDetails";
}
@Html.Action("CategoryListNavbar", "Category")
<div id="mainBody">
    <div class="container">
        <div class="row">
            <!-- Sidebar ================================================== -->
            <div id="sidebar" class="span3">
                @Html.Action("Summary", "Cart")
                <ul id="sideManu" class="nav nav-tabs nav-stacked">
                    @Html.Action("CategoryList", "Category")
                </ul>
                <br>

            </div>
            <!-- Sidebar end=============================================== -->
            <div class="span9">
                <ul class="breadcrumb">
                    <li><a href="index.html">Home</a> <span class="divider">/</span></li>
                    <li><a href="products.html">Products</a> <span class="divider">/</span></li>
                    <li class="active">product Details</li>
                </ul>
                <div class="row">
                    <div id="gallery" class="span3">
                        <a href="themes/images/products/large/f1.jpg" title="Fujifilm FinePix S2950 Digital Camera">
                            <img src="~/Content/image/@Model.Image" style="width:100%" alt="Fujifilm FinePix S2950 Digital Camera">
                        </a>
                        <div id="differentview" class="moreOptopm carousel slide">

                        </div>

                    </div>
                    <div class="span6">
                        <h3>@Model.Name.ToUpper() </h3>
                        <small>@Model.Category.Description.ToUpper()</small>
                        <hr class="soft">
                        <form class="form-horizontal qtyFrm">
                            <div class="control-group">
                                <label class="control-label"><span>@Model.Price (₺)</span></label>
                                <div class="controls">
                                    <input type="number" class="span1" placeholder="Qty.">
                                </div>
                            </div>
                        </form>

                        <hr class="soft">
                        <h4>@Model.Class. Sınıf </h4>
                        <hr class="soft clr">
                        <p>
                            @Model.Description
                        </p>
                        @using (Html.BeginForm("AddToCart", "Cart"))
                        {
                            @Html.HiddenFor(i => i.Id)
                            <button type="submit" class="btn btn-large btn-primary pt-md-2"> Sepete ekle <i class=" icon-shopping-cart"></i></button>
                        }

                    </div>

                </div>
            </div>
            @Html.Action("FeaturedProductList", "Home")
        </div>
    </div>
</div>

KarcicegiYayinVeDagitim/Views/Home/ProductList.cshtml
@using KarcicegiYayinVeDagitim.Entity
@model IEnumerable<Product>
@{
    ViewBag.Title = "ProductList";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@Html.Action("CategoryListNavbar", "Category")
<div id="mainBody">
    <div class="container">
        <div class="row">
            <!-- Sidebar ================================================== -->
            <div id="sidebar" class="span3">
                @Html.Action("Summary", "Cart")
                <ul id="sideManu" class="nav nav-tabs nav-stacked">
                    @Html.Action("CategoryList", "Category")
                </ul>
                <br>
            </div>
            <!-- Sidebar end=============================================== -->
            <div class="span9">
                <ul class="breadcrumb">
                    <li><a href="index.html">Home</a> <span class="divider">/</span></li>
                    <li class="active">Products Name</li>
                </ul>
                <h3> Kitap isimleri </h3>

                <br class="clr">
                <div class="tab-content">
                    <div class="tab-pane  active" id="blockView">
                        <ul class="thumbnails">

                            @foreach (var item in Model)
                            {
                                <li class="span3">
                                    <div class="thumbnail" style="width:270px;height:310px">
                                        <a href="/Home/ProductDetails/@item.Id"><img style="width:160px;height:200px;max-width:160px;max-height:250px" src="~/Content/image/@item.Image" alt="" /></a>
                                        <div class="caption" style="width:260px;height:140px">
                                            <h5><a href="/Home/ProductDetails/@item.Id">@item.Name.ToUpper() </a></h5>
                                            <p>
                                                @item.Description.ToUpper()
                                            </p>

                                            <h4 style="text-align:center"><a class="btn" href="/Home/ProductDetails/@item.Id">Görüntüle..<i class="icon-shopping-cart"></i></a> <a class="btn btn-primary">@item.Price (₺)</a></h4>
                                        </div>
                                    </div>
                                </li>
                            }
                        </ul>
                        <hr class="soft">
                    </div>
                </div>
                <br class="clr">
            </div>
            @Html.Action("FeaturedProductList", "Home")
        </div>
    </div>
</div>

KarcicegiYayinVeDagitim/Views/Home/Search.cshtml
@using KarcicegiYayinVeDagitim.Entity
@model IEnumerable<Product>
@{
    ViewBag.Title = "Search";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div id="mainBody">
    <div class="container">
        <div class="row">
            <!-- Sidebar ================================================== -->
            <div id="sidebar" class="span3">
                <div class="well well-small"><a id="myCart" href="product_summary.html"><img src="/Kaynak/themes/images/ico-cart.png" alt="cart">3 Items in your cart  <span class="badge badge-warning pull-right">$155.00</span></a></div>
                <ul id="sideManu" class="nav nav-tabs nav-stacked">
                    @Html.Action("CategoryList", "Category")
                </ul>
                <br>
                @Html.Action("FeaturedProductList", "Home")
            </div>
            <!-- Sidebar end=============================================== -->
            <div class="span9">
                <ul class="breadcrumb">
                    <li><a href="index.html">Home</a> <span class="divider">/</span></li>
                    <li class="active">Products Name</li>
                </ul>
                <h3> Ürün isimleri </h3>


                <br class="clr">
                <div class="tab-content">
                    <div class="tab-pane  active" id="blockView">
                        <ul class="thumbnails">
                            @foreach (var item in Model)
                            {

                                <li class="span3">
                                    <div class="thumbnail" style="width:270px;height:310px">
                                        <a href="/Home/ProductDetails/@item.Id"><img style="width:160px;height:200px;max-width:160px;max-height:250px" src="~/Content/image/@item.Image" alt="" /></a>
                                        <div class="caption" style="width:260px;height:140px">
                                            <h5><a href="/Home/ProductDetails/@item.Id">@item.Name</a></h5>
                                            <p>
                                                @item.Description
                                            </p>

                                            <h4 style="text-align:center"><a class="btn" href="/Home/ProductDetails/@item.Id">Görüntüle..<i class="icon-shopping-cart"></i></a> <a class="btn btn-primary">@item.Price (₺)</a></h4>
                                        </div>
                                    </div>
                                </li>
                            }
                        </ul>
                        <hr class="soft">
                    </div>
                </div>
                <br class="clr">
            </div>
        </div>
    </div>
</div>

KarcicegiYayinVeDagitim/Views/Home/Slider.cshtml
@using KarcicegiYayinVeDagitim.Entity
@model IEnumerable<Product>

<div id="carouselBlk">
    <div id="myCarousel" class="carousel slide">
        <div class="carousel-inner">
            <div class="item active">
                <div class="container">
                    <a href="#"><img style="width:100%" src="~/Content/image/Karçiçeği1_676x260.jpg" alt="special offers" /></a>
                </div>
            </div>
            @foreach (var item in Model)
            {
                <div class="item">
                    <div class="container">
                        <table>
                            <tr>
                                <td>
                                    <a href="/Home/ProductDetails/@item.Id">
                                        <div align="left"><img src="~/Content/image/@item.Image" style="width:100%;"  /> </div>
                                    </a>
                                </td>
                                <td>
                                    <a href="/Home/ProductDetails/@item.Id">
                                        <div align="right"><img src="~/Content/image/indirim.jpg" style="width:100%;" /> </div>
                                    </a>
                                </td>
                            </tr>
                        </table>
                        <div class="carousel-caption">
                            <h4></h4>
                            <p></p>
                        </div>
                    </div>
                </div>
            }
        </div>
        <a class="left carousel-control" href="#myCarousel" data-slide="prev">&lsaquo;</a>
        <a class="right carousel-control" href="#myCarousel" data-slide="next">&rsaquo;</a>
    </div>
</div>