KarcicegiYayinVeDagitim/Controllers/OrderController.cs
using KarcicegiYayinVeDagitim.Entity;
using KarcicegiYayinVeDagitim.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace KarcicegiYayinVeDagitim.Controllers
{
    public class OrderController : Controller
    {
        DataContext db = new DataContext();
        [Authorize(Roles = "admin")]
        // GET: Order
        public ActionResult Index()
        {
            var orders = db.Orders.Select(i => new AdminOrderModel()
            {
                Id = i.Id,
                OrderNumber = i.OrderNumber,
                OrderDate = i.OrderDate,
                OrderState = i.OrderState,
                Total = i.Total,
                Count = i.OrderLines.Count
            }).OrderByDescending(i => i.OrderDate).ToList();
            return View(orders);
        }
        public ActionResult Details(int id)
        {
            var entity = db.Orders.Where(i => i.Id == id).Select(i => new OrderDetailsModel()
            {
                OrderId = i.Id,
                OrderNumber = i.OrderNumber,
                Total = i.Total,
                UserName = i.UserName,
                OrderDate = i.OrderDate,
                OrderState = i.OrderState,
                AdresBasligi = i.AdresBasligi,
                Adres = i.Adres,
                Sehir = i.Sehir,
                Semt = i.Semt,
                Mahalle = i.Mahalle,
                PosteKodu = i.PosteKodu,
                OrderLines = i.OrderLines.Select(x => new OrderLineModel()
                {
                    ProductId = x.ProductId,
                    Image = x.Product.Image,
                    ProductName = x.Product.Name,
                    Quantity = x.Quantity,
                    Price = x.Price
                }).ToList()

            }).FirstOrDefault();
            return View(entity);
        }
        public ActionResult UpdateOrderState(int OrderId, EnumOrderState orderState)
        {
            var order = db.Orders.FirstOrDefault(i => i.Id == OrderId);
            if (order != null)
            {
                order.OrderState = orderState;
                db.SaveChanges();
                TempData["mesaj"] = "Bilgileriniz kaydedildi.";
                return RedirectToAction("Details", new {id = OrderId });
            }
            return RedirectToAction("Index");
        }
        public ActionResult BekleyenSiparisler()
        {
            var orders = db.Orders.Where(i => i.OrderState == EnumOrderState.Bekleniyor).ToList();
            return View(orders);
        }
        public ActionResult KargolananSiparisler()
        {
            var orders = db.Orders.Where(i => i.OrderState == EnumOrderState.Kargolandı).ToList();
            return View(orders);
        }
        public ActionResult TamamlananSiparisler()
        {
            var orders = db.Orders.Where(i => i.OrderState == EnumOrderState.Tamamlandı).ToList();
            return View(orders);
        }
        public ActionResult PaketlenenSiparisler()
        {
            var orders = db.Orders.Where(i => i.OrderState == EnumOrderState.Paketlendi).ToList();
            return View(orders);
        }
    }
}

KarcicegiYayinVeDagitim/Views/Order/BekleyenSiparisler.cshtml
@model IEnumerable<KarcicegiYayinVeDagitim.Entity.Order>
@{
    ViewBag.Title = "BekleyenSiparisler";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<div class="row">
    <div class="col-xs-12">
        <div class="box">
            <!--/.box-header-->
            <div class="box-body">
                <table id="example1" class="table table-bordered table-striped">
                    <thead>
                        <tr>
                            <th>Id</th>
                            <th>Sipariş Numarası</th>
                            <th>Sipariş Tarihi</th>
                            <th>Sipariş Durumu</th>
                            <th>Toplam Tutar (₺)</th>
                            <th></th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in Model)
                        {
                            <tr>
                                <td>
                                    @item.Id
                                </td>
                                <td>
                                    @item.OrderNumber
                                </td>
                                <td>
                                    @item.OrderDate
                                </td>
                                <td>
                                    @item.OrderState
                                </td>
                                <td>
                                    @item.Total
                                </td>
                                <td>
                                    @Html.ActionLink("Detay","Details",new { id = @item.Id }, new {@class="btn btn-primary"})
                                </td>
                            </tr>
                        }
                    </tbody>
                    <tfoot>
                        <tr>
                            <th>Id</th>
                            <th>Sipariş Numarası</th>
                            <th>Sipariş Tarihi</th>
                            <th>Sipariş Durumu</th>
                            <th>Toplam Tutar (₺)</th>
                            <th></th>
                        </tr>
                    </tfoot>
                </table>
            </div><!-- /.box-body -->
        </div><!-- /.box -->
    </div><!-- /.col -->
</div><!-- /.row -->

KarcicegiYayinVeDagitim/Views/Order/Details.cshtml
@using KarcicegiYayinVeDagitim.Models
@model OrderDetailsModel
@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<div>
    <h4>Sipariş Bilgileri</h4>
    <hr />
    <div class="row">
        @if (TempData["mesaj"] != null)
        {
            <div class="alert alert-success alert-dismissable">
                <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
                <h4>	<i class="icon fa fa-check"></i> Başarılı!</h4>
                Bilgileriniz Kaydedildi..
            </div>
        }
    </div>
    <dl class="dl-horizontal">
        <dt>
            Sipariş Durumu :
        </dt>

        <dd>
            @using (Html.BeginForm("UpdateOrderState", "Order", FormMethod.Post))
            {
                @Html.HiddenFor(i => i.OrderId)
                @Html.EnumDropDownListFor(i => i.OrderState, "Sipariş Durumu Seç", new { @class = "form-control" })
                <button type="submit" class="btn btn-primary">Güncelle</button>
            }
        </dd>
        <dt>
            Kullanıcı Adı :
        </dt>

        <dd>
            @Model.UserName
        </dd>
        <dt>
            Sipariş Numarası :
        </dt>

        <dd>
            @Html.DisplayFor(Model => Model.OrderNumber)
        </dd>
        <dt>
            Toplam Tutar :
        </dt>

        <dd>
            @Html.DisplayFor(Model => Model.Total)
        </dd>
        <dt>
            Sipariş Tarihi :
        </dt>

        <dd>
            @Html.DisplayFor(Model => Model.OrderDate)
        </dd>
        <dt>
            Adres :
        </dt>

        <dd>
            Adres Başlığı:  @Html.DisplayFor(Model => Model.AdresBasligi)
            <br />
            Adres:          @Html.DisplayFor(Model => Model.Adres)
            <br />
            Şehir:          @Html.DisplayFor(Model => Model.Sehir)
            <br />
            İlçe:           @Html.DisplayFor(Model => Model.Semt)
            <br />
            Mahalle:        @Html.DisplayFor(Model => Model.Mahalle)
            <br />
            Posta Kodu:     @Html.DisplayFor(Model => Model.PosteKodu)
            <br />
        </dd>

    </dl>
</div>

<table id="compairTbl" class="table table-bordered">
    <thead>
        <tr>
            <th>Resim</th>
            <th>Ürün Adı</th>
            <th>Toplam Fiyat (₺)</th>
            <th>Adet</th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model.OrderLines)
        {
            <tr>
                <td><img src="~/Content/image//@item.Image" height="75" width="50" /></td>>
                <td>@item.ProductName</td>>
                <td>@item.Price ₺</td>>
                <td>@item.Quantity</td>>
                <td>
                    <a href="/Home/ProductDetails/@item.ProductId" class="btn btn-primary" target="_blank">Ürün Detay</a>
                </td>>
            </tr>
        }

    </tbody>
</table>

KarcicegiYayinVeDagitim/Views/Order/Index.cshtml
@using KarcicegiYayinVeDagitim.Models
@model IEnumerable<AdminOrderModel>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<div class="row">
    <div class="col-xs-12">
        <div class="box">
            <!--/.box-header-->
            <div class="box-body">
                <table id="example1" class="table table-bordered table-striped">
                    <thead>
                        <tr>
                            <th>ID</th>
                            <th>Sipariş Numarası</th>
                            <th>Sipariş Tarihi</th>
                            <th>Sipariş Durumu</th>
                            <th>Toplam Tutar (₺)</th>
                            <th>Ürün Sayısı</th>
                            <th></th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in Model)
                        {
                        <tr>
                            <td>
                                @item.Id
                            </td>
                            <td>
                                @item.OrderNumber
                            </td>
                            <td>
                                @item.OrderDate
                            </td>
                            <td>
                                @item.OrderState
                            <td>
                                @item.Total ₺
                            </td>
                            <td>
                                @item.Count
                            </td>
                            <td>
                                <a class="btn btn-primary btn-sm" href="@Url.Action("Details",new { id = item.Id })"><i class="fa fa-fw fa-edit"></i>Detay Sayfası</a>
                            </td>
                        </tr>
                        }
                    </tbody>
                    <tfoot>
                        <tr>
                            <th>ID</th>
                            <th>Sipariş Numarası</th>
                            <th>Sipariş Tarihi</th>
                            <th>Sipariş Durumu</th>
                            <th>Toplam Tutar (₺)</th>
                            <th>Ürün Sayısı</th>
                            <th></th>
                        </tr>
                    </tfoot>
                </table>
            </div><!-- /.box-body -->
        </div><!-- /.box -->
    </div><!-- /.col -->
</div><!-- /.row -->

KarcicegiYayinVeDagitim/Views/Order/KargolananSiparisler.cshtml
@model IEnumerable<KarcicegiYayinVeDagitim.Entity.Order>
@{
    ViewBag.Title = "KargolananSiparisler";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<div class="row">
    <div class="col-xs-12">
        <div class="box">
            <!--/.box-header-->
            <div class="box-body">
                <table id="example1" class="table table-bordered table-striped">
                    <thead>
                        <tr>
                            <th>Id</th>
                            <th>Sipariş Numarası</th>
                            <th>Sipariş Tarihi</th>
                            <th>Sipariş Durumu</th>
                            <th>Toplam Tutar (₺)</th>
                            <th></th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in Model)
                        {
                            <tr>
                                <td>
                                    @item.Id
                                </td>
                                <td>
                                    @item.OrderNumber
                                </td>
                                <td>
                                    @item.OrderDate
                                </td>
                                <td>
                                    @item.OrderState
                                </td>
                                <td>
                                    @item.Total
                                </td>
                                <td>
                                    @Html.ActionLink("Detay", "Details", new { id = @item.Id }, new { @class = "btn btn-primary" })
                                </td>
                            </tr>
                        }
                    </tbody>
                    <tfoot>
                        <tr>
                            <th>Id</th>
                            <th>Sipariş Numarası</th>
                            <th>Sipariş Tarihi</th>
                            <th>Sipariş Durumu</th>
                            <th>Toplam Tutar (₺)</th>
                            <th></th>
                        </tr>
                    </tfoot>
                </table>
            </div><!-- /.box-body -->
        </div><!-- /.box -->
    </div><!-- /.col -->
</div><!-- /.row -->

KarcicegiYayinVeDagitim/Views/Order/PaketlenenSiparisler.cshtml
@model IEnumerable<KarcicegiYayinVeDagitim.Entity.Order>
@{
    ViewBag.Title = "PaketlenenSiparisler";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<div class="row">
    <div class="col-xs-12">
        <div class="box">
            <!--/.box-header-->
            <div class="box-body">
                <table id="example1" class="table table-bordered table-striped">
                    <thead>
                        <tr>
                            <th>Id</th>
                            <th>Sipariş Numarası</th>
                            <th>Sipariş Tarihi</th>
                            <th>Sipariş Durumu</th>
                            <th>Toplam Tutar (₺)</th>
                            <th></th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in Model)
                        {
                            <tr>
                                <td>
                                    @item.Id
                                </td>
                                <td>
                                    @item.OrderNumber
                                </td>
                                <td>
                                    @item.OrderDate
                                </td>
                                <td>
                                    @item.OrderState
                                </td>
                                <td>
                                    @item.Total
                                </td>
                                <td>
                                    @Html.ActionLink("Detay", "Details", new { id = @item.Id }, new { @class = "btn btn-primary" })
                                </td>
                            </tr>
                        }
                    </tbody>
                    <tfoot>
                        <tr>
                            <th>Id</th>
                            <th>Sipariş Numarası</th>
                            <th>Sipariş Tarihi</th>
                            <th>Sipariş Durumu</th>
                            <th>Toplam Tutar (₺)</th>
                            <th></th>
                        </tr>
                    </tfoot>
                </table>
            </div><!-- /.box-body -->
        </div><!-- /.box -->
    </div><!-- /.col -->
</div>

KarcicegiYayinVeDagitim/Views/Order/TamamlananSiparisler.cshtml
@model IEnumerable<KarcicegiYayinVeDagitim.Entity.Order>
@{
    ViewBag.Title = "TamamlananSiparisler";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

    <div class="row">
        <div class="col-xs-12">
            <div class="box">
                <!--/.box-header-->
                <div class="box-body">
                    <table id="example1" class="table table-bordered table-striped">
                        <thead>
                            <tr>
                                <th>Id</th>
                                <th>Sipariş Numarası</th>
                                <th>Sipariş Tarihi</th>
                                <th>Sipariş Durumu</th>
                                <th>Toplam Tutar (₺)</th>
                                <th></th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var item in Model)
                            {
                                <tr>
                                    <td>
                                        @item.Id
                                    </td>
                                    <td>
                                        @item.OrderNumber
                                    </td>
                                    <td>
                                        @item.OrderDate
                                    </td>
                                    <td>
                                        @item.OrderState
                                    </td>
                                    <td>
                                        @item.Total
                                    </td>
                                    <td>
                                        @Html.ActionLink("Detay", "Details", new { id = @item.Id }, new { @class = "btn btn-primary" })
                                    </td>
                                </tr>
                            }
                        </tbody>
                        <tfoot>
                            <tr>
                                <th>Id</th>
                                <th>Sipariş Numarası</th>
                                <th>Sipariş Tarihi</th>
                                <th>Sipariş Durumu</th>
                                <th>Toplam Tutar (₺)</th>
                                <th></th>
                            </tr>
                        </tfoot>
                    </table>
                </div><!-- /.box-body -->
            </div><!-- /.box -->
        </div><!-- /.col -->
    </div>